version: '3.7'
services:

  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    networks:
      - family-network
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5440:5432'

  python:
    container_name: family_python
    build:
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1

    depends_on:
      - postgres
    volumes:
      - ${PROJECT_VOLUME_SRC}:/app:cached
    networks:
      - family-network

volumes:
  family_db_volume:
    external: false
networks:
  family-network:
    driver: bridge
