version: '3.7'
services:
    postgres:
        image: postgres:13.3
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5440:5432'

volumes:
  db:
    driver: local
